# Generated by Django 4.2.14 on 2024-08-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0003_product_features_delete_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="persian_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
