# Generated by Django 4.2.14 on 2024-08-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0004_product_persian_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="price", field=models.IntegerField(),
        ),
    ]
