# Generated by Django 4.2.14 on 2024-08-10 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0006_cart_cartitem"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="product",),
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="licenses.cart",
            ),
        ),
        migrations.AddField(
            model_name="order", name="trackId", field=models.IntegerField(default=0),
        ),
    ]
