# Generated by Django 4.2.14 on 2024-08-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0008_alter_order_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
